version: '2'
services:
    web:
        build: .
        ports:
          - "8889:80"
        links:
          - postgres:postgres
    postgres:
        image: postgres:9.6.1
        environment: 
          - POSTGRES_PASSWORD=root
